# Generated by Django 3.0.8 on 2020-07-24 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_item_is_publish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['id']},
        ),
    ]
